### ISSUE TITLE
Rewrite/Cleanup BDU

### ISSUE THREAD

**Issue by Belhun** [Belhun/Armco-Halo-Mod#2]
I want to reorganize the BDU/Uniform Code for ARMCO and make sure the code works and is Easier to Read. 

- [ ] Fix Both Colonial DBUs so they have the same Name
- [x] Make sure it Works
- [x] Easier to Read(hopefully)

BDUs to be Remade
- [ ] Alpha BDU [Woodland]
- [ ] Alpha EOD BDU [Woodland]
- [ ] Alpha Medical BDU [Woodland]
- [ ] ODST BDU [Black]
- [ ] ODST BDU [Camo]
- [ ] ODST BDU [M90 Splinter Camo]
- [ ] Phoenix BDU [Olive]
- [ ] Phoenix EOD BDU [Olive]
- [ ] Phoenix Medical BDU [Olive]
- [ ] Sabre BDU [Olive]
- [ ] Sabre EOD BDU [Olive]
- [ ] Sabre Medical BDU [Olive]
- [ ] Zulu BDU [Camo]
- [ ] Zulu BDU [Woodland]
- [ ] Zulu EOD BDU [Camo]
- [ ] Zulu EOD BDU [Woodland]
- [ ] Zulu Meidcal BDU [Camo]
- [ ] Zulu Medical BDU [Woodland]

Optional if not redone Make a new Issue in Requests
- [ ] [Colonial Fire Department] BDU
- [ ] [Colonial Rescure] Medical BDU
- [ ] [Colonial Rescure] Police BDU 
- [ ] Security Bureau ODST BDU [Black/Gold]
- [ ] Security Tacial Overalls

**Comment by mrtrubshaw** [comment]
Armco BDU's recoded, textures still need to be done in future and the colonial things haven't been done

**Comment by Belhun** [comment]
working on OSDT-based uniforms

**Comment by Belhun** [comment]
Up storage on uniforms?
